services:
  db:
    container_name: magic-circle-backend-dev-db
    image: "mariadb:10.9"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    name: "magic-circle-backend-dev-db"
