"""rarity-special

Revision ID: cd46828bfd2b
Revises: 2b164321f7f1
Create Date: 2024-09-08 14:24:54.570645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd46828bfd2b'
down_revision: Union[str, None] = '2b164321f7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carddb', 'rarity',
               existing_type=mysql.ENUM('common', 'uncommon', 'rare', 'mythic'),
               type_=sa.Enum('common', 'uncommon', 'rare', 'mythic', 'special', name='rarity'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carddb', 'rarity',
               existing_type=sa.Enum('common', 'uncommon', 'rare', 'mythic', 'special', name='rarity'),
               type_=mysql.ENUM('common', 'uncommon', 'rare', 'mythic'),
               existing_nullable=False)
    # ### end Alembic commands ###
